name: Trigger Netlify Build
on:
  schedule:
    - cron: '0 0,12 * * *' # midday and midnight every day
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/6003590e87c131966024e151